### ISSUE TITLE
Occasional exception: ValueError: Invalid file descriptor: -1

### ISSUE THREAD

**Issue by davidosomething** [mhinz/neovim-remote#57] opened 2017-08-17 04:25 UTC
```
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=False debug=False>>
Traceback (most recent call last):
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/asyncio/base_events.py", line 512, in __del__
    self.close()
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/asyncio/unix_events.py", line 63, in close
    super().close()
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/asyncio/selector_events.py", line 110, in close
    self._close_self_pipe()
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/asyncio/selector_events.py", line 120, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/asyncio/selector_events.py", line 279, in _remove_reader
    key = self._selector.get_key(fd)
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/selectors.py", line 189, in get_key
    return mapping[fileobj]
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/selectors.py", line 70, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/Users/davidosomething/.local/pyenv/versions/3.6.2/lib/python3.6/selectors.py", line 41, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

**Comment by mhinz** [comment] 2017-09-13 15:46
Repro steps?

**Comment by mhinz** [comment] 2017-09-30 12:22
I can't reproduce it, but it would be interesting to know if it still happens with the latest neovim-remote v1.8.4.

That version double-checks if a given Unix domain is valid by trying to connect to it first and using a temporary socket should that fail.

**Comment by mhinz** [comment] 2017-10-07 12:52
Since there's nothing I can do about this without further information, I'm closing this.

Please reopen if you still think it's an issue in neovim-remote.

**Closed by mhinz** 2017-10-07 12:52 UTC
Labels: waiting:repro

**Comment by rudyryk** [comment] 2018-06-30 09:54
I get similar exception sometimes in the following case:

```python
def sample_task(self, name: str, payload: dict):
    loop = asyncio.new_event_loop()
    coro = asyncio.sleep(1.0, loop=loop)
    result = loop.run_until_complete(coro)
    # loop.close()  # uncomment this line to avoid edge case with __del__
    return result
```

Looks like a kind of edge case with ``BaseEventLoop.__del__``.

Note the line ``loop.close()`` before returning result. In my case solution was to close loop explicitly!

**Comment by rudyryk** [comment] 2018-07-01 17:51
@mhinz I didn't use ``neovim`` actually, I just googled similar bug and thought it would be helpful :)
