### ISSUE TITLE
--Remote-wait-silent doesn't seem to work

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#36] opened 2017-03-17 02:28 UTC
I run the following commands outside of any nvim instance:

```sh
nvr --remote-silent file.txt
```
and it opens file.txt without showing an error message, as expected.

But `nvr --remote-wait-silent file.txt` shows the error message and then opens file.txt.

**Comment by mhinz** [comment] 2017-03-19 16:06
Oh, hm. The argument parser expected the wrong arguments.

Should be fixed now, thanks!

**Comment by mhinz** [comment] 2017-03-22 12:14
I'm pretty sure it's fixed, so I'm closing this.

Thanks for your constant feedback. :-)

**Closed by mhinz** 2017-03-22 12:14 UTC

**Comment by Alok** [comment] 2017-03-22 21:42
Oh, I forgot to close this.

Thanks for constantly implementing it =).

**Comment by mhinz** [comment] 2018-04-11 21:34
I'm grateful enough for people taking the time to report errors, so.. I don't mind closing issues myself, as long as I'm fairly certain the issue is fixed. :-)

**Comment by Alok** [comment] 2018-04-11 21:36
It's kind of funny actually because I seem to only do it to your repos.
